name: sautiflow
description: High-fidelity, cross-platform Dart/Flutter audio engine for audiophiles, powered by miniaudio and native C++ FFI.
version: 0.6.7
homepage: https://sautiflow.nett.to
repository: https://github.com/wambugu71/sautiflow
issue_tracker: https://github.com/wambugu71/sautiflow/issues
topics:
  - audio
  - miniaudio
  - audiophiles
  - equalizer
  - music

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  meta: ^1.15.0
  http: ^1.6.0
  ffi: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: any

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
