/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-123196-gba38fa206e-20260306"
#endif /* AVUTIL_FFVERSION_H */
