/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-126207-g21bbd98e7b-20260818"
#endif /* AVUTIL_FFVERSION_H */
