name: Build Sautiplay Releases

on:
  push:
    tags:
      - "v*"
    branches:
      - main
      - master
      - alpha-experimental-release
  workflow_dispatch:

permissions:
  contents: write

jobs:
  delay:
    name: Delay for Package Publish
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 10 minutes to allow package publishing
        run: sleep 600

  build-android:
    name: Build Android
    needs: delay
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install published package
        working-directory: ./sautiplay
        run: |
          flutter pub remove sautiflow
          flutter pub add sautiflow

      - name: Install dependencies
        working-directory: ./sautiplay
        run: flutter pub get

      - name: Generate Splash & Launcher Icons
        working-directory: ./sautiplay
        run: |
          dart run flutter_launcher_icons
          dart run flutter_native_splash:create

      - name: Build Android APK
        working-directory: ./sautiplay
        run: flutter build apk --release --obfuscate --split-debug-info=build/debug_symbols --target-platform android-arm,android-arm64 --split-per-abi --dart-define="STREAM_URL_1=${{ secrets.STREAM_URL_1 }}" --dart-define="STREAM_URL_2=${{ secrets.STREAM_URL_2 }}"

      - name: Rename APK Artifacts
        working-directory: ./sautiplay
        run: |
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/sautiflow_android_armv7.apk
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/sautiflow_android_arm64.apk

      - name: Upload Artifact ARMv7
        uses: actions/upload-artifact@v4
        with:
          name: sautiflow_android_armv7
          path: sautiplay/build/app/outputs/flutter-apk/sautiflow_android_armv7.apk

      - name: Upload Artifact ARM64
        uses: actions/upload-artifact@v4
        with:
          name: sautiflow_android_arm64
          path: sautiplay/build/app/outputs/flutter-apk/sautiflow_android_arm64.apk

  build-windows:
    name: Build Windows
    needs: delay
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install published package
        working-directory: .\sautiplay
        run: |
          flutter pub remove sautiflow
          flutter pub add sautiflow

      - name: Install dependencies
        working-directory: .\sautiplay
        run: flutter pub get
      - name: Upgrade  dependencies
        working-directory: .\sautiplay
        run: flutter pub upgrade

      - name: Generate Splash & Launcher Icons
        working-directory: .\sautiplay
        run: |
          dart run flutter_launcher_icons
          dart run flutter_native_splash:create

      - name: Build Windows
        working-directory: .\sautiplay
        run: flutter build windows --release --no-pub --obfuscate --split-debug-info=build/debug_symbols --dart-define="STREAM_URL_1=${{ secrets.STREAM_URL_1 }}" --dart-define="STREAM_URL_2=${{ secrets.STREAM_URL_2 }}"

      - name: Compress Release
        working-directory: .\sautiplay\build\windows\x64\runner
        run: Compress-Archive -Path Release -DestinationPath sautiflow_windows.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sautiflow_windows
          path: sautiplay\\build\\windows\\x64\\runner\\sautiflow_windows.zip

  build-linux:
    name: Build Linux
    needs: delay
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libcurl4-openssl-dev
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install published package
        working-directory: ./sautiplay
        run: |
          flutter pub remove sautiflow
          flutter pub add sautiflow

      - name: Install dependencies
        working-directory: ./sautiplay
        run: flutter pub get

      - name: Upgrade  dependencies
        working-directory: ./sautiplay
        run: flutter pub upgrade
      - name: Generate Splash & Launcher Icons
        working-directory: ./sautiplay
        run: |
          dart run flutter_launcher_icons
          dart run flutter_native_splash:create

      - name: Build Linux
        working-directory: ./sautiplay
        run: flutter build linux --release --no-pub --obfuscate --split-debug-info=build/debug_symbols --dart-define="STREAM_URL_1=${{ secrets.STREAM_URL_1 }}" --dart-define="STREAM_URL_2=${{ secrets.STREAM_URL_2 }}"

      - name: Compress Release
        working-directory: ./sautiplay/build/linux/x64/release
        run: tar -czvf sautiflow_linux.tar.gz bundle

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sautiflow_linux
          path: sautiplay/build/linux/x64/release/sautiflow_linux.tar.gz

  build-macos:
    name: Build macOS
    needs: delay
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install published package
        working-directory: ./sautiplay
        run: |
          flutter pub remove sautiflow
          flutter pub add sautiflow

      - name: Install dependencies
        working-directory: ./sautiplay
        run: flutter pub get

      - name: Upgrade  dependencies
        working-directory: ./sautiplay
        run: flutter pub upgrade

      - name: Generate Splash & Launcher Icons
        working-directory: ./sautiplay
        run: |
          dart run flutter_launcher_icons
          dart run flutter_native_splash:create

      - name: Build macOS
        working-directory: ./sautiplay
        run: flutter build macos --release --no-pub --obfuscate --split-debug-info=build/debug_symbols --dart-define="STREAM_URL_1=${{ secrets.STREAM_URL_1 }}" --dart-define="STREAM_URL_2=${{ secrets.STREAM_URL_2 }}"

      - name: Compress Release
        working-directory: ./sautiplay/build/macos/Build/Products/Release
        run: zip -r sautiflow_macos.zip *.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sautiflow_macos
          path: sautiplay/build/macos/Build/Products/Release/sautiflow_macos.zip

  build-ios:
    name: Build iOS
    needs: delay
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install published package
        working-directory: ./sautiplay
        run: |
          flutter pub remove sautiflow
          flutter pub add sautiflow

      - name: Install dependencies
        working-directory: ./sautiplay
        run: flutter pub get

      - name: Upgrade  dependencies
        working-directory: ./sautiplay
        run: flutter pub upgrade

      - name: Generate Splash & Launcher Icons
        working-directory: ./sautiplay
        run: |
          dart run flutter_launcher_icons
          dart run flutter_native_splash:create

      - name: Build iOS
        working-directory: ./sautiplay
        run: flutter build ios --release --no-pub  --no-codesign --obfuscate  --split-debug-info=build/debug_symbols --no-codesign --dart-define="STREAM_URL_1=${{ secrets.STREAM_URL_1 }}" --dart-define="STREAM_URL_2=${{ secrets.STREAM_URL_2 }}"

      - name: Create unsigned IPA
        working-directory: ./sautiplay/build/ios/iphoneos
        run: |
          mkdir Payload
          cp -r Runner.app Payload/
          zip -qr sautiflow_ios.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sautiflow_ios
          path: sautiplay/build/ios/iphoneos/sautiflow_ios.ipa

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-android, build-windows, build-linux, build-macos, build-ios]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/sautiflow_android_armv7/sautiflow_android_armv7.apk
            artifacts/sautiflow_android_arm64/sautiflow_android_arm64.apk
            artifacts/sautiflow_windows/sautiflow_windows.zip
            artifacts/sautiflow_linux/sautiflow_linux.tar.gz
            artifacts/sautiflow_macos/sautiflow_macos.zip
            artifacts/sautiflow_ios/sautiflow_ios.ipa
          draft: false
          prerelease: false
